### ISSUE TITLE
C++ Parser?

### ISSUE THREAD

**Issue by jelling** [aws/amazon-kinesis-video-streams-parser-library#100]
Is there a corresponding parser library for C++? I have looked everywhere and cannot find one or an example of how to parse Kinesis Video streams using the AWS C++ SDK.

**Comment by MushMal** [comment]
Unfortunately no. We have been recommending customers to use 3rd party open source parsers to parse the outgoing MKV.

**Comment by jelling** [comment]
Such as?

**Comment by MushMal** [comment]
* libMatroska https://github.com/Matroska-Org/libmatroska
* libmkv https://github.com/quadrifoglio/libmkv
* libwebm (Googles implementation) https://chromium.googlesource.com/webm/libwebm/+/libwebm-1.0.0.26/mkvparser.cpp


There are others. We can't really endorse any one of these unfortunately. 

We are looking at providing a super lightweight KVS specific MKV parser in native C at some stage.
