### ISSUE TITLE
Using jcodec (or ffmpeg) to convert aac audio tracks to PCM

### ISSUE THREAD

**Issue by ajhool** [aws/amazon-kinesis-video-streams-parser-library#102]
Examples in this library include references for using JCodec to convert h264 to JPEG. Are there any similar examples for using JCodec (or ffmpeg) to decode the AAC audio produced by KVS GStreamer Plugin into PCM using jcodec or ffmpeg?

We have tried to write the audio track bytes directly to a file (eg. `streamingOutput.aac`) but media tools like ffmpeg or VLC have not been able to interpret the aac correctly. Our end goal is to write this audio to AWS Transcribe, which requires PCM.

**Comment by MushMal** [comment]
@ajhool, sorry, we don't have an example of audio. There are multiple AAC decoders (some with a license) that you can search for and try using. 

Regarding the file playback... You could use HLS/MPEG-DASH capability to get live playback (non-realtime) on many devices which have built-in players.

**Comment by MushMal** [comment]
Resolving as no further action
