### ISSUE TITLE
[Question] Parsing frame along with producer timestamp

### ISSUE THREAD

**Issue by gai6948** [aws/amazon-kinesis-video-streams-parser-library#116]
I am new to the library and I want to extract frames in the fragment from GetMedia API, along with the producer timestamp associated with the frame, is there a minimal example for that? Or which classes I should look for?

What I want to do with the library is to capture the frame and producer timestamp, and pass them as bytes into another Kinesis Stream which will be processed by a Lambda. I have an implementation in Python but I cannot capture the producer timestamp from the raw MKV, so I am looking at this library.

Thanks in advance.

**Comment by disa6302** [comment]
@gai6948  ,

This might be helpful: 

https://github.com/aws-samples/amazon-kinesis-video-streams-demos/blob/master/canary/consumer-java/src/main/java/com/amazon/kinesis/video/canary/consumer/CanaryFrameProcessor.java

**Comment by gai6948** [comment]
Thanks very much
