### ISSUE TITLE
Periodic delay in getting kinesis video stream

### ISSUE THREAD

**Issue by utsavrai** [aws/amazon-kinesis-video-streams-parser-library#119]
Hi,
I am experiencing a periodic delay in the frames received by the parser code provided by aws https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/examples-renderer.html, I tried to change the source camera on the sender/producer side and I also tried setting different fps and resolution but the streamed video gets a constant periodic lag/pause after every 3-4 seconds. Is this issue related to producer code or the parser code? Is there any change/enhancement can be done?

Thank you

**Comment by lcintron** [comment]
likely due to the h264decoder in the library.

**Comment by stefankiesz** [comment]
Hello, apologies for the late response, is this still an issue?
