### ISSUE TITLE
SLF4J: Class path contains multiple SLF4J bindings. issue when trying to execute KinesisVideoRendererExample test

### ISSUE THREAD

**Issue by leo7322** [aws/amazon-kinesis-video-streams-parser-library#125]
I followed the instruction from the tutorial  https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/examples-renderer.html.
However, when I tried to execute the KinesisVideoRendererExample test in the 6th step, I got the error below.
![螢幕擷取畫面 (175)](https://user-images.githubusercontent.com/54980665/129661598-35be306f-2ffc-4851-9d21-2bc75735b6ab.png)
Does anyone know this issue?
Also, if the information isn't clear enough, please let me know.
Thanks.

**Comment by swethasree8** [comment]
@leo7322 Did you find any solution? For me also same issue but tests are passed

**Comment by leo7322** [comment]
@swethasree8 No, I did not find a solution. Instead, I found an alternative. Since I was trying to use the GetMedia API in this library, I use the following resources. https://github.com/aws-samples/amazon-kinesis-video-streams-media-viewer
For your information.

**Comment by gtapizquent** [comment]
Running into this same issue.

**Comment by sirknightj** [comment]
Just ran this sample following the documentation, verified the media in the aws management console, and did not see those warning log lines. Please try the latest and see if the issue persists. If it does, please let us know!

**Comment by sirknightj** [comment]
Additional testing info: Tested both using IntelliJ and using command line, didn't see anything either time:
```
mvn test -Dtest=KinesisVideoRendererExampleTest
```
```
[INFO] --- surefire:3.1.2:test (default-test) @ amazon-kinesis-video-streams-parser-library ---
[INFO] Using auto detected provider org.apache.maven.surefire.testng.TestNGProvider
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.amazonaws.kinesisvideo.parser.examples.KinesisVideoRendererExampleTest
[WARNING] Tests run: 3, Failures: 0, Errors: 0, Skipped: 2, Time elapsed: 12.87 s -- in com.amazonaws.kinesisvideo.parser.examples.KinesisVideoRendererExampleTest
[INFO] 
[INFO] Results:
[INFO] 
[WARNING] Tests run: 3, Failures: 0, Errors: 0, Skipped: 2
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  16.907 s
[INFO] Finished at: 2023-09-19T20:51:55-07:00
[INFO] ------------------------------------------------------------------------
```
