### ISSUE TITLE
[QUESTION] Low frame quality returned by H264FrameDecoder

### ISSUE THREAD

**Issue by mrgiba** [aws/amazon-kinesis-video-streams-parser-library#126]
Hello,

On my tests using the library to process the stream data and run an Object Detection algorithm, I noticed that some of frames returned by the H264FrameDecoder are pretty grainy, definitely affecting the overall results

For comparison, I extracted a clip from the stream and ffmpeg on the command line to extract the frames and the resulting quality was way better

Does anyone know how to better handle the issue ?

Thanks

**Comment by stefankiesz** [comment]
Hello, apologies for the late response, is this still an issue we can assist you with?

**Comment by mrgiba** [comment]
Nope, that was wrong usage of the library

This issue can be closed
