### ISSUE TITLE
Release 1.0.16 not available on Maven

### ISSUE THREAD

**Issue by mcosicaws** [aws/amazon-kinesis-video-streams-parser-library#139]
The latest version of amazon-kinesis-video-streams-parser-library on Maven https://mvnrepository.com/artifact/com.amazonaws/amazon-kinesis-video-streams-parser-library is v1.0.15. When could we expect v1.0.16 to be available in Maven?

**Comment by mcosicaws** [comment]
POM has not been updated, it's still v1.0.15:
https://github.com/aws/amazon-kinesis-video-streams-parser-library/blob/master/pom.xml#L17

**Comment by altesean** [comment]
Any chance we can have this published, I see 1.1.0 is also missing?

**Comment by hassanctech** [comment]
v1.1.0 has been available for some time.  Closing this issue.
