### ISSUE TITLE
[QUESTION] log4j issues with latest 1.2.4

### ISSUE THREAD

**Issue by brandontyler** [aws/amazon-kinesis-video-streams-parser-library#163]
With the latest 1.2.4 I am receiving the following errors in my CloudWatch logs in AWS:

log4j:ERROR Could not instantiate class [com.amazonaws.services.lambda.runtime.log4j.LambdaAppender]
log4j:ERROR Could not instantiate appender named "LAMBDA".
log4j:ERROR Could not find value for key log4j.appender.CONSOLE
log4j:ERROR Could not instantiate appender named "CONSOLE".
log4j:WARN No appenders could be found for logger (com.amazonaws.kinesisvideo.parser.examples.GetMediaWorker)

Can anyone recommend what I am doing wrong.  I just updated some of the dependencies and I'm getting the above errors.
POM:

  <properties>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <dependencies>
    <dependency>
      <groupId>com.amazonaws</groupId>
      <artifactId>aws-lambda-java-log4j2</artifactId>
      <version>1.5.1</version>
    </dependency>
    <dependency>
      <groupId>org.apache.logging.log4j</groupId>
      <artifactId>log4j-core</artifactId>
      <version>2.17.1</version>
    </dependency>
    <dependency>
      <groupId>org.apache.logging.log4j</groupId>
      <artifactId>log4j-api</artifactId>
      <version>2.17.1</version>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-core</artifactId>
      <version>2.12.3</version>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
      <version>2.12.3</version>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-annotations</artifactId>
      <version>2.12.3</version>
    </dependency>
    <dependency>
      <groupId>com.amazonaws</groupId>
      <artifactId>aws-java-sdk</artifactId>
      <version>1.9.6</version>
    </dependency>
    <dependency>
      <groupId>com.amazonaws</groupId>
      <artifactId>amazon-kinesis-video-streams-parser-library</artifactId>
      <version>1.2.4</version>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
      <version>1.7.36</version>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-simple</artifactId>
      <version>1.7.36</version>
    </dependency>
    <dependency>
      <groupId>com.amazonaws</groupId>
      <artifactId>aws-java-sdk-s3</artifactId>
      <version>1.12.212</version>
    </dependency>
  </dependencies>

**Comment by brandontyler** [comment]
Actually, I ran a dependency analytics report and it recommended I upgrade Jackson to 2.13.3.  same errors though

**Comment by brandontyler** [comment]
Anyone have any thoughts on this? I looked at some of the recent check-ins and noticed someone else had done some changing to make this error I think go away.

**Comment by CGarces** [comment]
Try

```xml
<dependency>
    <groupId>com.amazonaws</groupId>
    <artifactId>aws-lambda-java-log4j</artifactId>
    <version>1.0.0</version>
</dependency>
```

See #124 for context
Please not close the issue, look like this dependency not is correctly documented.

**Comment by niyatim23** [comment]
Closing since the version has been upgraded
