### ISSUE TITLE
[BUG] Upgrade  com.google.protobuf:protobuf-java /  io.netty:netty-handler

### ISSUE THREAD

**Issue by BoyeMagnus** [aws/amazon-kinesis-video-streams-parser-library#169]
Various of outdated packages is introduced to this package, is there any way to update these / to get com.amazonaws:amazon-kinesis-client to update their packages?
![WBS 2022-12-28 at 20 06 40](https://user-images.githubusercontent.com/24491343/209860518-8a5f245a-acff-4fc4-907f-231ff50ca618.png)

![WBS 2022-12-28 at 20 07 05](https://user-images.githubusercontent.com/24491343/209860547-da3a4ed3-677d-4ee6-b7b1-88987b46eaba.png)

**Comment by BoyeMagnus** [comment]
<img width="373" alt="WBS 2023-02-21 at 15 06 03@2x" src="https://user-images.githubusercontent.com/24491343/220367331-c36c4315-c481-44bf-a73b-68784bb81d3c.png">


New issues caused by outdated dependencies. Proper patch management should be implemented

**Comment by niyatim23** [comment]
Closing this issue as the PR has been merged
