### ISSUE TITLE
Sample Dockerfile available?

### ISSUE THREAD

**Issue by Alex-Wenner-FHR** [aws/amazon-kinesis-video-streams-parser-library#173]
Hello!

This is a great library and very verbose. I am new to the KVS but have been able to follow documentation [here](https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp) and get a CPP container running and publishing streams to AWS KVS successfully. This works great!

I am at a point now where I want to put a process out there to consume these streams that are being published for analysis. After doing some searching I found this repository and being that it is as well written and documented as it is, I would much rather use something like this then trying to leverage boto3 and the available APIs do redo this process myself. 

With that said, would it be possible to provide a sample Dockerfile as seen [here for the CPP producer](https://github.com/aws-samples/amazon-kinesis-video-streams-demos/tree/master/producer-cpp/docker-amazonlinux)? I think a sample Dockerfile would be a great help and steer me in the right direction. If this already exists please point me to it! Thanks!

**Comment by Alex-Wenner-FHR** [comment]
I understand how to compile and build now. No longer needed

**Comment by gem-aniketyadav** [comment]
Hi @Alex-Wenner-FHR  can you provide the Dockerfile here as well. It would be a lot of help.
