### ISSUE TITLE
Unable to Build using Provided Instructions

### ISSUE THREAD

**Issue by faizhassan-ibex** [aws/amazon-kinesis-video-streams-parser-library#180]
Hi - Good day. I'm struggling with build for quite a while. I've fully functionally dev environment equipped with :

1. Java 2.x (20.0.1)
2. Apache Maven 3.9.2
3. Able to Build and Run S3Client Project
4. Tried different lombok versions
Below is the error returned and build failed:  mvn clean install

\BoundingBoxImagePanel.java [delomboked]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  9.188 s
[INFO] Finished at: 2023-06-21T16:43:12+05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.projectlombok:lombok-maven-plugin:1.18.20.0:delombok (delombok) on project amazon-kinesis-video-streams-parser-library: Unable to delombok: InvocationTargetException: var -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by niyatim23** [comment]
Hi @faizhassan-ibex, can you try building it with Java 8?

**Comment by flaviut** [comment]
Ran into this as well--switching to OpenJDK 8 worked fine.
