### ISSUE TITLE
[QUESTION] mvn install fails on mac and al2023-ami

### ISSUE THREAD

**Issue by AwsMLMaster** [aws/amazon-kinesis-video-streams-parser-library#189]
mvn install fails. both on my macbook and ec2 G5.xlarge with al2023-ami
mvn version: 3.9.6
java version: 21
changing pom.xml to latest version (except lombok-maven-plugin where max is 1.18.20.0) of Lombok didn't work as well.

** Logging ** 
[ec2-user@ip-172-31-8-250 amazon-kinesis-video-streams-parser-library]$ mvn clean
[INFO] Scanning for projects...
[INFO] 
[INFO] -----< com.amazonaws:amazon-kinesis-video-streams-parser-library >------
[INFO] Building Amazon Kinesis Video Streams Parser Library 1.2.5
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- clean:3.2.0:clean (default-clean) @ amazon-kinesis-video-streams-parser-library ---
[INFO] Deleting /home/ec2-user/amazon-kinesis-video-streams-parser-library/target
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.351 s
[INFO] Finished at: 2024-02-03T19:43:47Z
[INFO] ------------------------------------------------------------------------
[ec2-user@ip-172-31-8-250 amazon-kinesis-video-streams-parser-library]$ mvn install
[INFO] Scanning for projects...
[INFO] 
[INFO] -----< com.amazonaws:amazon-kinesis-video-streams-parser-library >------
[INFO] Building Amazon Kinesis Video Streams Parser Library 1.2.5
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] Parameter 'annotationProcessorPaths' is unknown for plugin 'maven-shade-plugin:3.2.4:shade (default)'
[INFO] 
[INFO] --- lombok:1.18.20.0:delombok (delombok) @ amazon-kinesis-video-streams-parser-library ---
Copying resource file: com/amazonaws/kinesisvideo/parser/examples/.DS_Store
/home/ec2-user/amazon-kinesis-video-streams-parser-library/src/main/java/com/amazonaws/kinesisvideo/parser/mkv/Frame.java:80: error: cannot find symbol
    private static FrameBuilder getBuilderWithCommonParams(ByteBuffer simpleBlockDataBuffer) {
                   ^
  symbol:   class FrameBuilder
  location: class com.amazonaws.kinesisvideo.parser.mkv.Frame
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.173 s
[INFO] Finished at: 2024-02-03T19:44:02Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.projectlombok:lombok-maven-plugin:1.18.20.0:delombok (delombok) on project amazon-kinesis-video-streams-parser-library: Unable to delombok: InvocationTargetException: java.lang.NoSuchFieldError: Class com.sun.tools.javac.tree.JCTree$JCImport does not have member field 'com.sun.tools.javac.tree.JCTree qualid' -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

** Any design considerations/constraints **
None 

** If you would not like to open an issue to discuss your solution in open-platform, please email your question to kinesis-video-support@amazon.com **

**Comment by AwsMLMaster** [comment]
Solved:
Using Java 1.8, mvn 3.8.8

**Comment by sirknightj** [comment]
Thanks for the feedback. We'll look into updating the documentation for this.
