### ISSUE TITLE
[BUG} 

### ISSUE THREAD

**Issue by Lyllt8** [aws/amazon-kinesis-video-streams-parser-library#192]
**Logging**
Add relevent parser library logging.  IMPORTANT NOTE:  Please make sure to NOT share AWS access credentials under any circumstance!  Please make sure they are not in the logs.

**Describe the bug**

**SDK version number**
Include the SDK version you are running. If it is a specific commit on master branch, include that

**Open source building**
If it is a build issue, include 3rd party library version and steps to how you are building it

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by stefankiesz** [comment]
There is nothing filled in the issue form, closing.
