### ISSUE TITLE
Cannot build project on Windows using Eclipse

### ISSUE THREAD

**Issue by pflugs30** [aws/amazon-kinesis-video-streams-parser-library#20]
OS: Windows 10 64-bit
JDK: 1.8.0_152
IDE: Eclipse IDE for Java Developers, Version: Oxygen.3 Release (4.7.3)

I'm trying to build the Java Streams Parser Library following [these steps](https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/parser-library-download.html).  I started with a fresh install of [Eclipse](https://www.eclipse.org/downloads/download.php?file=/oomph/epp/oxygen/R2/eclipse-inst-win64.exe).  I cloned the code from this Github repo locally, and imported it into Eclipse.  I received the following error:

```
Execution delombok of goal org.projectlombok:lombok-maven-plugin:1.16.18.1:delombok failed: A required class was missing while executing org.projectlombok:lombok-maven-plugin:1.16.18.1:delombok: com/sun/tools/javac/util/Context
-----------------------------------------------------
realm =    plugin>org.projectlombok:lombok-maven-plugin:1.16.18.1
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
urls[0] = file:/C:/Users/mpflu/.m2/repository/org/projectlombok/lombok-maven-plugin/1.16.18.1/lombok-maven-plugin-1.16.18.1.jar
urls[1] = file:/C:/Users/mpflu/.m2/repository/org/apache/commons/commons-lang3/3.6/commons-lang3-3.6.jar
urls[2] = file:/C:/Users/mpflu/.m2/repository/org/projectlombok/lombok/1.16.18/lombok-1.16.18.jar
urls[3] = file:/C:/Users/mpflu/.m2/repository/org/codehaus/plexus/plexus-utils/1.5.8/plexus-utils-1.5.8.jar
Number of foreign imports: 5
import: Entry[import org.sonatype.plexus.build.incremental from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import org.codehaus.plexus.util.Scanner from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import org.codehaus.plexus.util.DirectoryScanner from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import org.codehaus.plexus.util.AbstractScanner from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import  from realm ClassRealm[maven.api, parent: null]]

-----------------------------------------------------
 (org.projectlombok:lombok-maven-plugin:1.16.18.1:delombok:delombok:generate-sources)

org.apache.maven.plugin.PluginExecutionException: Execution delombok of goal org.projectlombok:lombok-maven-plugin:1.16.18.1:delombok failed: A required class was missing while executing org.projectlombok:lombok-maven-plugin:1.16.18.1:delombok: com/sun/tools/javac/util/Context
-----------------------------------------------------
realm =    plugin>org.projectlombok:lombok-maven-plugin:1.16.18.1
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
urls[0] = file:/C:/Users/mpflu/.m2/repository/org/projectlombok/lombok-maven-plugin/1.16.18.1/lombok-maven-plugin-1.16.18.1.jar
urls[1] = file:/C:/Users/mpflu/.m2/repository/org/apache/commons/commons-lang3/3.6/commons-lang3-3.6.jar
urls[2] = file:/C:/Users/mpflu/.m2/repository/org/projectlombok/lombok/1.16.18/lombok-1.16.18.jar
urls[3] = file:/C:/Users/mpflu/.m2/repository/org/codehaus/plexus/plexus-utils/1.5.8/plexus-utils-1.5.8.jar
Number of foreign imports: 5
import: Entry[import org.sonatype.plexus.build.incremental from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import org.codehaus.plexus.util.Scanner from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import org.codehaus.plexus.util.DirectoryScanner from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import org.codehaus.plexus.util.AbstractScanner from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import  from realm ClassRealm[maven.api, parent: null]]

-----------------------------------------------------

	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:168)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:331)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1362)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1360)
	at org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant.build(MojoExecutionBuildParticipant.java:52)
	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:137)
	at org.eclipse.m2e.core.project.configurator.AbstractLifecycleMapping.configure(AbstractLifecycleMapping.java:111)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$3.call(ProjectConfigurationManager.java:508)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$3.call(ProjectConfigurationManager.java:1)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:501)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.configureNewMavenProjects(ProjectConfigurationManager.java:288)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$1.call(ProjectConfigurationManager.java:175)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$1.call(ProjectConfigurationManager.java:1)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1355)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.importProjects(ProjectConfigurationManager.java:143)
	at org.eclipse.m2e.core.ui.internal.wizards.ImportMavenProjectsJob$1.doCreateMavenProjects(ImportMavenProjectsJob.java:68)
	at org.eclipse.m2e.core.ui.internal.wizards.AbstractCreateMavenProjectsOperation.run(AbstractCreateMavenProjectsOperation.java:73)
	at org.eclipse.m2e.core.ui.internal.wizards.ImportMavenProjectsJob.runInWorkspace(ImportMavenProjectsJob.java:77)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: org.apache.maven.plugin.PluginContainerException: A required class was missing while executing org.projectlombok:lombok-maven-plugin:1.16.18.1:delombok: com/sun/tools/javac/util/Context
-----------------------------------------------------
realm =    plugin>org.projectlombok:lombok-maven-plugin:1.16.18.1
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
urls[0] = file:/C:/Users/mpflu/.m2/repository/org/projectlombok/lombok-maven-plugin/1.16.18.1/lombok-maven-plugin-1.16.18.1.jar
urls[1] = file:/C:/Users/mpflu/.m2/repository/org/apache/commons/commons-lang3/3.6/commons-lang3-3.6.jar
urls[2] = file:/C:/Users/mpflu/.m2/repository/org/projectlombok/lombok/1.16.18/lombok-1.16.18.jar
urls[3] = file:/C:/Users/mpflu/.m2/repository/org/codehaus/plexus/plexus-utils/1.5.8/plexus-utils-1.5.8.jar
Number of foreign imports: 5
import: Entry[import org.sonatype.plexus.build.incremental from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import org.codehaus.plexus.util.Scanner from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import org.codehaus.plexus.util.DirectoryScanner from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import org.codehaus.plexus.util.AbstractScanner from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import  from realm ClassRealm[maven.api, parent: null]]

-----------------------------------------------------

	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:166)
	... 27 more
Caused by: java.lang.NoClassDefFoundError: com/sun/tools/javac/util/Context
	at lombok.delombok.Delombok.<init>(Delombok.java:69)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at lombok.launch.Delombok.<init>(Delombok.java:32)
	at lombok.maven.AbstractDelombokMojo.execute(AbstractDelombokMojo.java:135)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 27 more
Caused by: java.lang.ClassNotFoundException: com.sun.tools.javac.util.Context
	at java.lang.ClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at lombok.launch.ShadowClassLoader.loadClass(ShadowClassLoader.java:422)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 36 more
```

If I try to build the application, I receive many more errors, mostly about a particular Class cannot be resolved to a type.

I saw [this issue](https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-java/issues/17#issuecomment-355473850), and I tried downloading lombok.jar, installing it (by double-clicking and loading to Eclipse using the Wizard).  I then re-cloned this repo and tried importing again.  I still get the same result.

Following the advice on [this SO article](https://stackoverflow.com/questions/10314904/no-com-sun-tools-javac-in-jdk7), I manually added the tools.jar package to the JDK version in Eclipse.  That had no effect.

Following the suggestion on [this SO article](https://stackoverflow.com/a/44942038), I added the JDK path to my System PATH, but that didn't work either.

What else can I try?

**Comment by zhiyua-git** [comment]
@pflugs30  Can you try this solution? It worked on my Windows EC2 version:
https://stackoverflow.com/questions/6565803/maven-delombok-issue-when-compiling-in-eclipse

It is changing JRE to JDK for Eclipse launch.

After adding this, you need to also **add lombok.jar as external library** in your Eclipse directory (Mine is C:\Users\Administrator\eclipse\java-oxygen\eclipse\lombok.jar), then clean the build, it should work.

Please let us know if it works. Also we have a future plan to remove lombok from dependency to avoid this kind of pain.

-ZH

**Comment by zhiyua-git** [comment]
@pflugs30  If the solution above doesn't work for you, you can also try removing this lines: https://github.com/aws/amazon-kinesis-video-streams-parser-library/blob/master/pom.xml#L124-L156.
If your lombok was set properly, then you should be able to compile without that target.

**Comment by pflugs30** [comment]
Hello @zhiyua-git,

Thanks for your response.  Now that I'm back in the office, I tried your suggestions.  Using the SO answer you posted, I changed my eclipse.ini file to the following:

`-vm C:\Program Files\Java\jdk1.8.0_152\bin\javaw.exe
`

Then, I relaunched Eclipse with a fresh clone of this library.  Using instructions on [this page](www.oxfordmathcenter.com/drupal7/node/44), I added lombok 1.16.18 (freshly downloaded from [the Lombok older versions website](https://projectlombok.org/downloads/lombok-1.16.18.jar)) as an External JAR.  I cleaned the project and then rebuilt, but I got the same error as before, sadly.

I checked the project's Build Path, and I noticed that it was using a JRE system library.  So, I removed the JRE and replaced it by clicking Add Library --> JRE System Library --> Workspace default JRE (jdk1.8.0_152).  I then cleaned and rebuilt my project, but that resulted in the same error again.

Finally, I commented lines 124 - 156 of pom.xml, cleaned, and rebuilt the project.  That removed the lombok error.  However, I still have 445 other errors, 444 of which are like this:

```
CompositeMkvElementVisitor cannot be resolved to a type
/amazon-kinesis-video-streams-parser-library/src/test/java/com/amazonaws/kinesisvideo/parser/mkv/visitors/CopyVisitorTest.java
```

There is one error like this:

```
The method getType(int) of type TestEBMLTypeInfoProvider must override or implement a supertype method.
/amazon-kinesis-video-streams-parser-library/src/test/java/com/amazonaws/kinesisvideo/parser/ebml/TestEBMLTypeInfoProvider.java
```

I'm not sure what else is the issue.  Could this still be related to Lombok?

**Comment by pflugs30** [comment]
I have made some progress.  I am able to build the application now and run the tests, so I know it's working.  I'm going to do a bit of testing on my end to be sure I can reproduce these results.  When I am satisfied that I can reproduce my success, I will post back steps as to what worked.

**Comment by zhiyua-git** [comment]
Glad to hear you can get the project built! It would be great if you post back steps worked for you.
And we are going to remove lombok dependency to avoid such kind of issue soon.

**Comment by pflugs30** [comment]
Okay, as best as I can figure, here are the steps I used to clone this library and build it on my laptop.  I will document them here to hopefully help the next Windows developer.  Please note that I am using Windows 10 64-bit, and I started with having **no Java JRE or JDK installations on my machine**.

1.  Download and install [Java SE Development Kit for Windows 64-bit](http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html).
 * I used 1.8.0_162 (8u162 on the downloads page - future versions will be different).
 * If you have other versions of JDK you don't want to / can't remove, you can leave them on your machine and add another step later.  I'd still recommend installing a JDK 1.8 version.
2.  Download and install [Eclipse](https://www.eclipse.org/downloads/download.php?file=/oomph/epp/oxygen/R2/eclipse-inst-win64.exe).
 * I used Oxygen.3 Release (4.7.3).
3.  Per [this SO article](https://stackoverflow.com/questions/6565803/maven-delombok-issue-when-compiling-in-eclipse), edit the `eclipse.ini` file in your Eclipse folder.  Change the path under the `-vm` argument to point to your JDK folder (if it isn't already pointing there).
 * If this argument doesn't exist, you will need to add it.
 * In my case, the file to change was at `C:\Users\{user_name}\eclipse\java-oxygen\eclipse\eclipse.ini`.
 * I used `-vm C:\Program Files\Java\jdk1.8.0_162\bin`.  **Note that in my case what worked was using the path to the folder bin folder - which is different from what the SO article referenced above shows in the main answer.
 * If you are using a specific JDK version, as in step #1 above, use the path to that version's bin folder. 
4.  Download [Lombok version 1.16.18](https://projectlombok.org/downloads/lombok-1.16.18.jar).  Install by opening the JAR file after it downloads and specifying Eclipse during the install.  Once installed, close the Lombok installer.
 * The exact version is used here because the code in this repository references this version.
5.  Open Eclipse to confirm it opens.  Click Help --> About Eclipse.  Scroll to the bottom of the About window, and confirm you see Lombok there.
 * I see "Lombok v1.16.18 "Dancing Elephant" is installed. https://projectlombok.org/".
6.  In Eclipse, go to Window --> Preferences --> Java --> Installed JREs.  Ensure that a JDK1.8 (preferably the one you installed in step #1 above) is selected.
 * If you only have one JDK version that you installed in step #1 above AND you set the `-vm` argument, you can most likely skip this step.
 * If you have multiple JREs listed OR you see a JRE (not JDK) selected, you can specify the JRE System Library to use in Eclipse.  See [this SO answer](https://stackoverflow.com/a/13636584).
7.  Clone this Github repository locally.
8.  Import the project into Eclipse using File --> Import --> Maven -- Existing Maven Projects.  Browse to the local repo, and selecting the `/pom.xml` file.  Then, click Finish.
9.  Once the project imports, attempt to build it (if it doesn't automatically build).
 * In my case, I saw 445 errors, most of which were 'cannot import type' errors.
 * To correct these errors, I needed to open one of the src files, such as `src\main\java\com\amazonaws\kinesisvideo\parser\ebml\EBMLParser.java`.
 * In the file, scroll up to the top of the page where the Import statements are.  You may have to expand the outlines.
 * Hold down CTRL and click on one of the Lombok Import statements, such as the word 'Getter' of `import lombok.Getter`.  In my case, Eclipse briefly displayed a message saying something like "Could not locate resource".  But after a brief pause, Eclipse seemed to find the Lombok code and displayed the contents of the JAR file related to the Import statement I clicked on.
 * Build the project again (CTRL + B on Windows).
 * The above steps were what finally got the project to compile for me.  It could have been something misconfigured on my machine (Maven perhaps?), but it's how I solved it.
 * Note: a subsequent Clean and Build of the project also resulted in no errors.
10.  If there are no further errors, test the project by executing one or more of the JUnit tests, such as `com.amazonaws.kinesisvideo.parser.EBMLParserTest.testEBMLElementInOneStep`.


I know this procedure is long, but it worked for me.  I admit that I have limited Java and Eclipse experience (I'm more into C#), and that probably contributed to my struggles.  I know this procedure works because I've tried it on three different Windows 10 machines now.  Hopefully it can help the next person.  :-)  Perhaps the readme.md could reference this comment?
