### ISSUE TITLE
Streams Parser Library Example code for NodeJS or Browser

### ISSUE THREAD

**Issue by pflugs30** [aws/amazon-kinesis-video-streams-parser-library#21]
I'm not sure if this issues list is the best / right place for this question, but I'll ask it anyway.  I appreciate very much the Streams Parser Java SDK.  It really helps me understand things better.

Is there another SDK or example project for retrieving / parsing / displaying media from a Video Stream in a NodeJS / browser application?  I'm essentially looking to create a version of the live streams viewer on the AWS Kinesis Video Streams console.  I've been unable to find any concrete "hello world" examples or tutorials.  I've read through the Developer Guide and API Reference documents, and I'm working through building my own browser-based tests now.  Ideally, I'd like to download a sample or tutorial project, point it at a video stream, and see a live feed in real-time.

Does something like that tutorial exist?  Any plans to create one?  Thanks again!
-Matthew

**Comment by MushMal** [comment]
@pflugs30 we are working on creating more samples and more documentation for various scenarios. One thing I would recommend is to reach out to kinesis-video-support@amazon.com for generic questions/comments.

**Comment by pflugs30** [comment]
Okay, thank you very much.

**Comment by brahama** [comment]
No news regarding NodeJS examples? Thanks

**Comment by SujithSizon** [comment]
Hello @pflugs30 @brahama any luck yet, were you guys able to write one on your own ?

**Comment by pflugs30** [comment]
Hello @SujithSizon.  No, I didn't pursue Kinesis with NodeJS any further at the time.  I stuck with the Java examples, and that was enough for our R&D efforts at the time.  I haven't worked with Kinesis video streams since.
