### ISSUE TITLE
Implementation on android

### ISSUE THREAD

**Issue by HelloEgg** [aws/amazon-kinesis-video-streams-parser-library#24]
Hi.

I am trying to view the streamed video from kinesis video to my android application.

Would there be a way to view stream data in my android application?

So far, my assumption is to 
1. make .jar file and implement it as library
or
2. Download all java files in android working directory

I doubt if simply implementing java file would work but Android-SDK does not seem to offer consumer side.

Thanks in advance!

**Comment by MushMal** [comment]
Hi @HelloEgg 

You might refer to the following entry: https://stackoverflow.com/a/50441828/964438

Unfortunately, we don't yet have a ready end-to-end example of a consumer application for Android. We are thinking of putting together a demo consumer application which would simply utilize the parser library and MediaCodec on Android for the playback.

**Comment by HelloEgg** [comment]
Thanks!

How would I be able to access video stream data?

Would I need to go through authentication process using aws-android-sdk?

Would there be a way my android access arn address of kineses-video?

**Comment by HelloEgg** [comment]
I mean, all I need to do is to access the preview screen from kinesis video streaming.

I was wondering if aws kinesis android sdk supports it or if I have to implement parser library, how I would be able to do it.. 

Thank you so much in advance!

**Comment by MushMal** [comment]
Unfortunately, AWS Android SDK doesn't have the ready code. You could use the Android Mobile SDK to make a series of calls to get the end point and issue GetMedia call. The data that's streamed in should then be passed through the parser library: https://github.com/aws/amazon-kinesis-video-streams-parser-library

The produced encoded frames then can be passed through MediaCodec to get decoded and then rendered on the screen. There are many alternatives to the decoding/rendering too. Please refer to the samples in the parser library to see the generic Java implementation based on JCodec.

**Comment by zhiyua-git** [comment]
Hi @HelloEgg ,

We have Http Live Streaming feature available now. You can refer to [here](https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/how-hls.html) for how this works. The EXO player on Android supports HLS playback. If you have any further question, feel free to open new issue or contact kinesis-video-support@amazon.com.

Thanks,
-ZH

**Comment by HelloEgg** [comment]
Hello @zhiyua-git 

Thank you very much on your reply! Happy to hear that kinesis supports HLS playback! 

I should definitely start on it in no time!

Best,

-Cholmin
