### ISSUE TITLE
cannot find symbol   symbol:   class FrameBuilder

### ISSUE THREAD

**Issue by fast4break** [aws/amazon-kinesis-video-streams-parser-library#25]
I cloned the amazon-kinesis-video-streams-parser-library and imported the project to my IDEA IDE. When I ran the example, it stopped at the following error:
---------------->
Error:(79, 20) java: cannot find symbol
  symbol:   class FrameBuilder
  location: class com.amazonaws.kinesisvideo.parser.mkv.Frame
<-----------------
Where can I find the class 'FrameBuilder'?

**Comment by sayantacC** [comment]
The  amazon-kinesis-video-streams-parser-library uses lombok to generate the builder pattern for the Frame class. You need to enable lombok for intellij. This stackoverflow answer describes how to enable lombok for intellij well: https://stackoverflow.com/a/27430992

It basically has two parts:
1. Enable annotation processing in intellij
2. Install the lombok plugin for intellij and restart.

**Comment by fast4break** [comment]
Thanks. I did above settings and downgraded java to 1.8, test was passed.
