### ISSUE TITLE
kinesisVideoRendererExample fails when startSelectorType is NOW

### ISSUE THREAD

**Issue by benzile** [aws/amazon-kinesis-video-streams-parser-library#26]
Hi there,
I have been trying to use the above example as a pattern to try and capture a stream from kinesis videos, visit each mkv element and then decode each h264 frame.
This works great while the start selectorType for the getMedia worker is at EARLIEST for example but will fail with the following when I try and get the newest data on the stream with startSelectorType of NOW:

11:03:10.755 [pool-2-thread-1] ERROR com.amazonaws.kinesisvideo.parser.examples.GetMediaWorker - Exception while accepting visitor {}
java.lang.NullPointerException: null
    at org.jcodec.codecs.h264.decode.BlockInterpolator.getBlockLuma(BlockInterpolator.java:41) ~[jcodec-0.2.2.jar:0.2.2]
    at org.jcodec.codecs.h264.decode.MBlockSkipDecoder.predictPSkip(MBlockSkipDecoder.java:91) ~[jcodec-0.2.2.jar:0.2.2]
    at org.jcodec.codecs.h264.decode.MBlockSkipDecoder.decodeSkip(MBlockSkipDecoder.java:45) ~[jcodec-0.2.2.jar:0.2.2]
    at org.jcodec.codecs.h264.decode.SliceDecoder.decode(SliceDecoder.java:126) ~[jcodec-0.2.2.jar:0.2.2]
    at org.jcodec.codecs.h264.decode.SliceDecoder.decodeMacroblocks(SliceDecoder.java:100) ~[jcodec-0.2.2.jar:0.2.2]
    at org.jcodec.codecs.h264.decode.SliceDecoder.decodeFromReader(SliceDecoder.java:73) ~[jcodec-0.2.2.jar:0.2.2]
    at org.jcodec.codecs.h264.H264Decoder$FrameDecoder.decodeFrame(H264Decoder.java:152) ~[jcodec-0.2.2.jar:0.2.2]
    at org.jcodec.codecs.h264.H264Decoder.decodeFrameFromNals(H264Decoder.java:103) ~[jcodec-0.2.2.jar:0.2.2]
    at com.amazonaws.kinesisvideo.parser.utilities.H264FrameRenderer.decodeH264Frame(H264FrameRenderer.java:73) ~[classes/:?]
    at com.amazonaws.kinesisvideo.parser.utilities.H264FrameRenderer.process(H264FrameRenderer.java:53) ~[classes/:?]
    at com.amazonaws.kinesisvideo.parser.utilities.FrameVisitor$FrameVisitorInternal.visit(FrameVisitor.java:69) ~[classes/:?]
    at com.amazonaws.kinesisvideo.parser.mkv.MkvDataElement.accept(MkvDataElement.java:128) ~[classes/:?]
    at com.amazonaws.kinesisvideo.parser.mkv.visitors.CompositeMkvElementVisitor.visitAll(CompositeMkvElementVisitor.java:63) ~[classes/:?]
    at com.amazonaws.kinesisvideo.parser.mkv.visitors.CompositeMkvElementVisitor.visit(CompositeMkvElementVisitor.java:54) ~[classes/:?]
    at com.amazonaws.kinesisvideo.parser.mkv.MkvDataElement.accept(MkvDataElement.java:128) ~[classes/:?]
    at com.amazonaws.kinesisvideo.parser.mkv.StreamingMkvReader.apply(StreamingMkvReader.java:132) ~[classes/:?]
    at com.amazonaws.kinesisvideo.parser.examples.GetMediaWorker.run(GetMediaWorker.java:69) [classes/:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
    at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_171]
    at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_171]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]

I am using the producer library(native API) on an ubunto 16.04 virtual box and in my example I disable the put media worker within the example and instead run a separate process that does the producing.

Any ideas???

thanks

**Comment by vijaygj** [comment]
Hello benzile@ can you please get the fragment number for which this is happening and share it with us? We can look into it. Specifically, I see some H264 decoding error - 

> at org.jcodec.codecs.h264.H264Decoder.decodeFrameFromNals(H264Decoder.java:103) ~[jcodec-0.2.2.jar:0.2.2]

As it is trying to decode the frame that means it is receiving data from GetMedia, so GetMedia call itself looks okay to me. However, I am not sure why the decoding is failing. If you can log the fragment number for which this is happening, we can check using a different start selector to see if it is fragment specific issue or GetMedia specific issue.

**Comment by benzile** [comment]
Hi there,
Thanks for the quick response.
When I run the parser in EARLIEST mode the first fragment number is (repeated and verified):
91343852333181432392682062612128579853214395080
To remind you, this is the start selector type that works well for the decoder.

When I run the parser in NOW mode the first fragment number is (this are two logs, it naturally changes each time i run it because of the NOW property):
91343852333181442479417502709407307892868285531
another example of this was 
91343852333181445415811275894329482170472670001
To remind you, this is the start selector type that breaks the decoder.

Now, I am not much of am encoding programmer))) but might it be that the fragments must start at a certain point for the decoder to be able to decode? meaning, the same way that the diff frames are dependent on the key frame within the h264 format, there is a dependency between the first fragment to those who follow it, and by visiting a first random fragment out of the entire video stream causes the decoder to break (unique encoding for this particular h264 stream that your project offers...?)

Hope this is enough information

Thanks!

**Comment by vijaygj** [comment]
Thank you for the details and helping debugging this issue.

> When I run the parser in NOW mode the first fragment number is (this are two logs, it naturally changes each time i run it because of the NOW property):

Fragment number changing for NOW is expected and your understanding is correct. 

Can you please run following GetMedia call? Just want to rule out if it is GetMedia issue or decoding issue. This will help to get data for same fragment (once it fails with start selector NOW, and later with the exact fragment number). If it indeed only fails with NOW, then we will check further details.

Can you run the GetMedia with fragment number - "91343852333181442479417502709407307892868285531" or any of the fragment number failing with? 

```
FRAGMENT_NUMBER - Start with the chunk containing the specific fragment. You must also specify the StartFragmentNumber. 
```

https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/API_dataplane_StartSelector.html#KinesisVideo-Type-dataplane_StartSelector-StartSelectorType

**Comment by vijaygj** [comment]
> Now, I am not much of am encoding programmer))) but might it be that the fragments must start at a certain point for the decoder to be able to decode?

GetMedia always start at the fragment boundary, so if there is no bug, decoding must work with all start selectors including NOW.

**Comment by benzile** [comment]
Hi,
I have basically removed the entire decoding operation from the flow of the getMediaWorker and it seems that it has no problem getting the fragments from Kinesis with any start selector type.
In my eyes it is most likely an encoding error.
To remind you, I have also disabled the put media worker in this example and I am using a video that I produce in a different process that is using the the producer JNI to to wrap the static h264 frames in your project, while the the renderer example originally used a pre made mkv file (clusters.mkv) . It is possible that the producer library is the one that is causing this bug or that that the h264 single frames are encoded a bit differently than the ones that are contained within the clusters.mkv file.
Trying to view the video stream in your AWS console seem to doesnt work on NOW mode either, the only way you can view the stream is by clicking the back to start button in the console.
Also, I ran the PutMediaDemo from the producer instead of the demoAppMain and both the console and the decoder were able to handle the NOW property.
To conclude,it seems that the problem is arising from the demoAppMain meaning from the native producer library.
Hope this helps

Thanks

**Comment by vijaygj** [comment]
Thank you for trying different inputs to help debug this issue.

> To conclude,it seems that the problem is arising from the demoAppMain meaning from the native producer library.

Can you please point me to the demo file that you are using? We would like to avoid this issue for other users and I am not sure which demoAppMain (or the input file) is not working with jcodec. We have replaced some original input files as they had the decoding error.

**Comment by benzile** [comment]
Hi,
I am using the aws sdk java producer library: 
https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-java
This project includes a linKinesisVideoProducerJNI.so(and mac and rasp versions as well), this JNI file is a compiled version of : 
https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp

Now, the first project has two main apps that it runs:
https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-java/tree/master/src/main/demo/com/amazonaws/kinesisvideo/demoapp

DemoAppMain - This app uses the producer JNI compiled file to handle encoding, MKv containing, time stamping and more. The input of this app is a static stream of h264 files which are collected and contained as fragments by the library and then uploaded via the put media api to kinesis video:
https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-java/tree/master/src/main/resources/data/h264

PutMediaDemo - This app doesnt use the JNI file and instead is receiving one MKV file that is chunked and then uploaded to kinesis video via the same put media api:
https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-java/tree/master/src/main/resources/data/mkv

My assumption is that via some sort of a bug in the native producer library(the JNI file) the containing of the h264 files is some how not quite right and therefore when the encoder is receiving the fragments not in a complete order it fails. What strengthen my suspicion is that the AWS console is unable(at least the times I tried it) to play the uploaded video stream in live mode and will only start playing once you run it to the start of the stream, which make me think it's not a jCodec issue but an encoding/containing issue by the JNI library.

The other option is that the h264 frames you use in the producer demoAppMain app are badly encoded in the first place.

This completes my thoughts  on this subject :-)

Thanks

**Comment by vijaygj** [comment]
Thanks. We will check the encoding issue for the demo files. Thanks for reporting the problem.

**Comment by vijaygj** [comment]
Can you please confirm the version of your java SDK? We have updated the demo files around March 15th for the issue you reported,

https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-java/commit/3e336120999e0ab64f91ff127efbcb90014381d9#diff-82b28c24f36003770b50a47ce541d72a

**Comment by benzile** [comment]
mine was cloned later than that....I see that at least release 1.0.4(april 2018) is included, I also see that it still has known issues with decoding certain mkv files...anyhow, will try to create my own stream of h264 and see how it goes...

**Comment by garishsood** [comment]
Hi @benzile, my name is Garish and I am the product manager for Kinesis VIdeo Streams. Thanks for your interest in kinesis video streams and we appreciate you taking out the time to provide valuable feedback to help us improve our service and demo app. Please let us know if you would like us to schedule a brief call to expedite the resolution of this issue.

At Amazon, we strongly believe in working backward from our customers and in that spirit, I would also love to hear more about your use case and get your thoughts on any enhancements that we can make to our service to better serve your needs.

Please feel free to send me a note at garisood@amazon.com and I would set-up time for us to connect.

**Comment by unicornss** [comment]
Closing this issue for now. Please reopen if required.
