### ISSUE TITLE
List of fragments

### ISSUE THREAD

**Issue by elohalili** [aws/amazon-kinesis-video-streams-parser-library#27]
I'm trying to retrieve the list of fragments from kinesis video stream using AWS SDK for NODE js.
This is what I am using:

```
var params = {
        StreamName: 'STRING_VALUE',
        /* required */
        FragmentSelector: {
                FragmentSelectorType: "SERVER_TIMESTAMP",
                TimestampRange: {
                        EndTimestamp: new Date(),
                        StartTimestamp: 0
                }
        }
};
kinesisvideoarchivedmedia.listFragments(params, function (err, data) {
        if (err) console.log(err, err.stack); // an error occurred
        else console.log(data); // successful response
});
```

I have tried with actual timestamps and switching between SERVER and PRODUCER timestamp in the "FragmentSelectorType" but the response is always a completely empty object.

If I try with the getMedia API specifying a timestamp of the stream it actually works, but how can I retrieve the list of archived media?
Thanks

**Comment by vijaygj** [comment]
Hello,

Can you please provide the region, requestIds and date and time for this issue? We will check our logs to confirm what is going on.

Thanks

**Comment by elohalili** [comment]
Hi,
I've figured it out after reviewing the entire code...
I didn't set up correctly the endpoint.

**Comment by unicornss** [comment]
Closing the issue for now. Please reopen if required
