### ISSUE TITLE
Is SDK available as JAR?

### ISSUE THREAD

**Issue by RafaelRViana** [aws/amazon-kinesis-video-streams-parser-library#29]
Hi,

The example contained in this repository, code are in com.amazonaws.kinesisvideo.parser.*

I found on Maven Repository this SDK:
```
<!-- https://mvnrepository.com/artifact/com.amazonaws/aws-java-sdk-kinesisvideo -->
<dependency>
    <groupId>com.amazonaws</groupId>
    <artifactId>aws-java-sdk-kinesisvideo</artifactId>
    <version>1.11.409</version>
</dependency>
```
But, in this SDK doesn't have a parser package.

To run the parser library outside of this example project, do I need to copy all code to there. Or do you have a JAR release version of project?

Thanks.

**Comment by RafaelRViana** [comment]
Thanks

**Comment by zhiyua-git** [comment]
Hi @RafaelRViana ,

Latest version is available in maven: https://mvnrepository.com/artifact/com.amazonaws/amazon-kinesis-video-streams-parser-library/1.0.9

Thanks,
-ZH
