### ISSUE TITLE
Java/ Maven requirements

### ISSUE THREAD

**Issue by laurenkemperman** [aws/amazon-kinesis-video-streams-parser-library#37]
What are the requirements for Java version, maven and others? I'm not able to successfully build this project with Java 11.0.1 and maven 3.2 (downgraded because of version specified in pom.xml file). 

Thanks!

**Comment by vijaygj** [comment]
Can you please share the compilation/build error that you are observing? Java 1.8+ should be able to compile/build the project.

One potential issue that I can speculate is IDE not having Lombok plugin and annotation preprocessing is not enabled. In that situation, mvn build will work, but IDE will show errors.

**Comment by laurenkemperman** [comment]
Hello, 

Thank you for your quick reply. I have attached the log output for running mvn clean install. 


Lauren

**Comment by vijaygj** [comment]
I do not see the log file attached.

**Comment by laurenkemperman** [comment]
Here it is again: 

Thanks!

**Comment by vijaygj** [comment]
I still could not find the log file. Please send it to kinesis-video-support@amazon.com .

I tried to reproduce it on OSX, but I see mvn clean; mvn install; working,

amazon-kinesis-video-streams-parser-library-1.0.8-sources.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 22.557 s
[INFO] Finished at: 2018-12-14T20:57:27-08:00
[INFO] Final Memory: 63M/739M
[INFO] ------------------------------------------------------------------------

**Comment by laurenkemperman** [comment]
Thanks for your assistance, I was able to build the project successfully on Mac with java 1.8. To run the example from the command line (without IDE) from this link: https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/examples-renderer.html <https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/examples-renderer.html>, I have tried to execute: 

mvn exec:java -Dexec.mainclass=KinesisVideoRendererExampleTest.Main -f ~/amazon-kinesis-video-streams-parser-library/pom.xml 

I received an error message: An exception occured while executing the Java class. org.baeldung.java.App while executing this command. Is this the proper way to execute the example, and if so do you have a suggestion for how to fix this? 

Thanks, 

Lauren

**Comment by laurenkemperman** [comment]
Thank you so much for your time, and edits to the pom file for this application. 

I will try this. I am looking to simply access the frames from a kinesis video ARN, and pass them to another process. Please let me know if you have any additional suggestions for doing this. 

Lauren

**Comment by vijaygj** [comment]
> I am looking to simply access the frames from a kinesis video ARN, and pass them to another process.

Can you please provide further details on what you are doing with the frames to kinesis-video-support@amazon.com ? and what is your use case? We are continuously looking to improve and would like to understand how can we make Kinesis video streams easier for you.

In meanwhile, here are some details to help you iterate faster.

You need to figure out how to include tests in the "shade" jar or simply copy test logic to a class in src directory like following,

Copying test details from following file,

https://github.com/aws/amazon-kinesis-video-streams-parser-library/blob/master/src/test/java/com/amazonaws/kinesisvideo/parser/examples/KinesisVideoGStreamerPiperExampleTest.java#L45 

```
diff --git a/src/main/java/RunProcess.java b/src/main/java/RunProcess.java
new file mode 100644
index 0000000..7c7da58
--- /dev/null
+++ b/src/main/java/RunProcess.java
@@ -0,0 +1,40 @@
+import com.amazonaws.kinesisvideo.parser.examples.KinesisVideoGStreamerPiperExample;
+import com.amazonaws.auth.profile.ProfileCredentialsProvider;
+//import com.amazonaws.kinesisvideo.parser.TestResourceUtil;
+import com.amazonaws.kinesisvideo.parser.ebml.InputStreamParserByteSource;
+import com.amazonaws.kinesisvideo.parser.ebml.MkvTypeInfos;
+import com.amazonaws.kinesisvideo.parser.mkv.MkvElementVisitException;
+import com.amazonaws.kinesisvideo.parser.mkv.StreamingMkvReader;
+import com.amazonaws.kinesisvideo.parser.mkv.visitors.CountVisitor;
+import com.amazonaws.regions.Regions;
+import lombok.Getter;
+
+import java.io.IOException;
+import java.io.InputStream;
+import java.nio.file.Files;
+import java.nio.file.Path;
+import java.nio.file.Paths;
+
+public class RunProcess {
+  public static void main(String[] args) throws Exception {
+        final Path outputFilePath = Paths.get("output_from_gstreamer-"+System.currentTimeMillis()+".mkv");
+        String gStreamerPipelineArgument =
+                "matroskademux ! matroskamux! filesink location=" + outputFilePath.toAbsolutePath().toString();
+
+        KinesisVideoGStreamerPiperExample example = KinesisVideoGStreamerPiperExample.builder().region(Regions.US_WEST_2)
+                .streamName("myTestStream2")
+                .credentialsProvider(new ProfileCredentialsProvider())
+                //.inputVideoStream(TestResourceUtil.getTestInputStream("clusters.mkv"))
+                .gStreamerPipelineArgument(gStreamerPipelineArgument)
+                .build();
+
+        example.execute();
+
+        //Verify that the generated output file has the expected number of segments, clusters and simple blocks.
+        CountVisitor countVisitor =
+                CountVisitor.create(MkvTypeInfos.SEGMENT, MkvTypeInfos.CLUSTER, MkvTypeInfos.SIMPLEBLOCK);
+        StreamingMkvReader.createDefault(new InputStreamParserByteSource(Files.newInputStream(outputFilePath)))
+.apply(countVisitor);
+  }
+}
+
```
And run the logic using following CLI command. It assumes you are using updated pom file from previous updates.

```
f45c89a55207% java -cp target/amazon-kinesis-video-streams-parser-library-1.0.8.jar RunProcess
```

In this case, input frames are sent to gstreamer pipeline as an example. However you can pick other examples to send the decoded frames to arbitrary process.

**Comment by MushMal** [comment]
Resolving as stale
