### ISSUE TITLE
Parser Maven Release is not Dependency Minimal

### ISSUE THREAD

**Issue by taylor-zr** [aws/amazon-kinesis-video-streams-parser-library#39]
+- com.amazonaws:amazon-kinesis-video-streams-parser-library:jar:1.0.8:compile
[INFO] |  +- org.apache.commons:commons-lang3:jar:3.6:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.10:compile
[INFO] |  +- com.amazonaws:aws-java-sdk:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-transcribe:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-autoscalingplans:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-workmail:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-servicediscovery:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-cloud9:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-serverlessapplicationrepository:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-alexaforbusiness:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-resourcegroups:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-comprehend:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-translate:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-sagemaker:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-iotjobsdataplane:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-sagemakerruntime:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-appsync:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-guardduty:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-mq:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-mediaconvert:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-mediastore:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-mediastoredata:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-medialive:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-mediapackage:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-costexplorer:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-pricing:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-mobile:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-cloudhsmv2:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-glue:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-migrationhub:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-dax:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-greengrass:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-athena:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-marketplaceentitlement:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-codestar:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-lexmodelbuilding:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-resourcegroupstaggingapi:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-pinpoint:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-xray:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-opsworkscm:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-support:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-simpledb:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-servicecatalog:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-servermigration:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-simpleworkflow:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-storagegateway:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-route53:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-importexport:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-sts:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-sqs:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-rds:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-redshift:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-elasticbeanstalk:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-glacier:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-iam:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-datapipeline:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-elasticloadbalancing:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-elasticloadbalancingv2:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-emr:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-elasticache:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-elastictranscoder:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-ec2:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-dynamodb:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-sns:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-budgets:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-cloudtrail:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-cloudwatch:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-logs:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-events:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-cognitoidentity:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-cognitosync:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-directconnect:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-cloudformation:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-cloudfront:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-clouddirectory:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-kinesis:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-opsworks:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-ses:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-autoscaling:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-cloudsearch:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-cloudwatchmetrics:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-codedeploy:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-codepipeline:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-config:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-lambda:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-ecs:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-ecr:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-cloudhsm:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-ssm:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-workspaces:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-machinelearning:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-directory:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-efs:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-codecommit:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-devicefarm:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-elasticsearch:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-waf:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-marketplacecommerceanalytics:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-inspector:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-iot:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-api-gateway:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-acm:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-gamelift:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-dms:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-marketplacemeteringservice:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-cognitoidp:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-discovery:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-applicationautoscaling:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-snowball:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-rekognition:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-polly:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-lightsail:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-stepfunctions:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-health:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-costandusagereport:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-codebuild:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-appstream:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-shield:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-batch:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-lex:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-mechanicalturkrequester:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-organizations:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-workdocs:jar:1.11.289:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-models:jar:1.11.289:compile
[INFO] |  |  \- com.amazonaws:aws-java-sdk-swf-libraries:jar:1.11.22:compile

Unless you're doing some crazy stuff, I'm guessing snowball isn't a dependency

This is an issue for Lambda projects, like Connect Media Streams integrations.

**Comment by bdhandap** [comment]
Hey @taylor-zr 

Thanks for bringing to our notice. We are already working on a fix to reduce the number of dependencies in Parser library and will be included in the next release.

**Comment by taylor-zr** [comment]
Thanks!

**Comment by zhiyua-git** [comment]
Hi @taylor-zr ,

We have updated the maven dependencies. Now the jar from latest release is about 24MB and has those unnecessary dependencies removed. If you find it still not working for your case, feel free to reopen or create a new issue.

Thanks,
-ZH
