### ISSUE TITLE
getMedia() works but getMediaForFragmentList() causes Exception though Fragmentlist is there

### ISSUE THREAD

**Issue by arnamoy10** [aws/amazon-kinesis-video-streams-parser-library#42]
First of all, I really like the prompt response from the peers in this forum.  Thank you.

I am stuck at the last step of code I am writing to store video for a timerange in a file.  I am following the guideline of the provided KinesisVideoExample code.  The provided code works and it stores the current stream into a video file using getMedia().

But when I modified the GetMediaWorker class to capture media for a list of fragments and used it to create the video in KinesisVideoExample, I am getting a `java.util.NoSuchElementException: No value present` exception.  Here's the only code that I modified:

``` java
public void run() {
        System.out.println("*****inside getmedia");
        int i = 1;
        try{
                 System.out.println("got here 1");
                //create timestamp range to get the fragments
                TimestampRange timestampRange = new TimestampRange();
                timestampRange.setStartTimestamp(new SimpleDateFormat("dd/MM/yyyy HH:mm:ss").parse("26/01/2019 1:57:15"));
                timestampRange.setEndTimestamp(new SimpleDateFormat("dd/MM/yyyy HH:mm:ss").parse("26/01/2019 1:58:02")); 
                FragmentSelector fragmentSelector = new FragmentSelector();
                 fragmentSelector.setFragmentSelectorType("SERVER_TIMESTAMP");
                 fragmentSelector.setTimestampRange(timestampRange);
                System.out.println("got here 2");
       

                 ListFragmentsRequest request = new ListFragmentsRequest();
                 request.setStreamName("evastream");
                 request.setFragmentSelector(fragmentSelector);
                 request.setMaxResults((long) 100);
                 request.setRequestCredentialsProvider(getCredentialsProvider());
                 System.out.println("got here 3");
                 ListFragmentsResult result_fragments = this.videoMedia1.listFragments(request);
            
                  //extract the fragment numbers in a list
                  List<Fragment> fragments = result_fragments.getFragments();
                  List<String> fragment_numbers = new ArrayList<String>();;
                  for (i = 0; i < fragments.size(); i++) {
                         fragment_numbers.add(fragments.get(i).getFragmentNumber());
                  }
                  System.out.println("got here 4");
                  System.out.println("Result");
                  System.out.println(fragment_numbers);   
            
        
                  //get the media and save to file
                 try {
                          log.info("Start GetMedia worker on stream {}", streamName);

                         GetMediaForFragmentListResult result = videoMedia2.getMediaForFragmentList(new GetMediaForFragmentListRequest().withStreamName("evastream").withFragments(fragment_numbers));
                         System.out.println("got here 5" + result);


                         StreamingMkvReader mkvStreamReader = StreamingMkvReader.createDefault(new InputStreamParserByteSource(result.getPayload()));

                         System.out.println("got here 6");

                         log.info("StreamingMkvReader created for stream {} ", streamName);
                         try {
                                 mkvStreamReader.apply(this.elementVisitor);
		                System.out.println("got here 7");

                         } catch (MkvElementVisitException e) {
                                 log.error("Exception while accepting visitor {}", e);
                         }
              } catch (Throwable t) {
                       log.error("Failure in GetMediaWorker for streamName {} {}", streamName, t.toString());
                       throw t;
             } finally {
                       log.info("Exiting GetMediaWorker for stream {}", streamName);
             }
        } .  catch (Exception e){
                    System.out.println("Got exception!!!!!!!!!!" + e);
        }
    }
```

And here's my output:
`
got here 1
got here 2
got here 3
got here 4
Result
[91343852333182130942439190729095929711417800847, 91343852333182130952342711043378974327665059005, 91343852333182130912728629786246795832790312052, 91343852333182130922632150100529840454139928736, 91343852333182130917680389943388318140851604430, 91343852333182130907776869629105273524258966667, 91343852333182130937487430571954407403121378283, 91343852333182130947390950886237452019294439540, 91343852333182130927583910257671362759149774872, 91343852333182130932535670414812885071857711056]
got here 5{ContentType: video/webm,Payload: com.amazonaws.event.ResponseProgressInputStream@13c04038}
got here 6
Got exception!!!!!!!!!!java.util.NoSuchElementException: No value present
`
Can anybody please help with that?  As seen from the output, I am getting the fragment list also the payload looks fine!  The exception occurs in this line: `mkvStreamReader.apply(this.elementVisitor);`

**Comment by bdhandap** [comment]
Hey @arnamoy10 ,

I think your `NoSuchElementException` is caused when you try to access contents of java `Optional` object but it's empty inside. Can you post the stack track here to help you better?

**Comment by arnamoy10** [comment]
Hi @bdhandap ;

Thanks for your answer.  I am sorry but I am really new to Java, can you please tell me how do I get the stack track?

Thanks

**Comment by bdhandap** [comment]
}  catch (Exception e){
                    System.out.println("Got exception!!!!!!!!!!" + e);
                   // Print stack trace
                   e.printStackTrace();
        }

**Comment by arnamoy10** [comment]
Hi @bdhandap 

`java.util.NoSuchElementException: No value present
	at java.util.OptionalLong.getAsLong(OptionalLong.java:118)
	at com.amazonaws.kinesisvideo.parser.examples.KinesisVideoExampleArnamoy$LogVisitor.visit(KinesisVideoExampleArnamoy.java:138)
	at com.amazonaws.kinesisvideo.parser.mkv.MkvEndMasterElement.accept(MkvEndMasterElement.java:36)
	at com.amazonaws.kinesisvideo.parser.mkv.visitors.CompositeMkvElementVisitor.visitAll(CompositeMkvElementVisitor.java:67)
	at com.amazonaws.kinesisvideo.parser.mkv.visitors.CompositeMkvElementVisitor.visit(CompositeMkvElementVisitor.java:49)
	at com.amazonaws.kinesisvideo.parser.mkv.MkvEndMasterElement.accept(MkvEndMasterElement.java:36)
	at com.amazonaws.kinesisvideo.parser.mkv.StreamingMkvReader.apply(StreamingMkvReader.java:132)
	at com.amazonaws.kinesisvideo.parser.examples.GetMediaWorkerFragments.run(GetMediaWorkerFragments.java:126)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by arnamoy10** [comment]
Figuring out from the stacktrace, it looks like `log.info("End of segment  {} fragment # {} millisBehindNow {} ", fragmentCount, fragmentMetadataVisitor.getCurrentFragmentMetadata().get().getFragmentNumberString(), fragmentMetadataVisitor.getMillisBehindNow().getAsLong());` line was giving the trouble, specially `getMillisBehindNow().getAsLong()` part, not sure why, but removing this line took care of the exception, but I have a new issue now which I am posting fresh.

**Comment by varun-tangoit** [comment]
Hi @arnamoy10 . can you please help me out, How to use getMediaForFragmentList() function to get list of fragments between timerange. While i try to use, i get error like 
2020-06-25 15:17:21 ERROR    GetMediaForFragmentListWorker:121 - Failure in GetMediaForFragmentListWorker for streamName 361bc35139241afa7519c6c3da79ded8 com.amazonaws.services.kinesisvideo.model.ResourceNotFoundException: The requested stream is not found or not active. (Service: AmazonKinesisVideoArchivedMedia; Status Code: 404; Error Code: ResourceNotFoundException; Request ID: b6208523-6511-48cb-9c72-9780fcaf2901)

is there any preconfiguration any required?

**Comment by arnamoy10** [comment]
@varun-tangoit Looks like the stream you are trying to access is not accessible somehow.  Can you see in the AWS console if the stream is present and is receiving data?

**Comment by varun-tangoit** [comment]
Yeah stream is active only. But when i try to use getMediaForFragmentList() function only i got this error

**Comment by MushMal** [comment]
Are you using the correct region and whether you have the rights? Could you please cut a separate issue? This one is unrelated to your question
