### ISSUE TITLE
Saving video from getMedia() vs getMediaForFragmentList()

### ISSUE THREAD

**Issue by arnamoy10** [aws/amazon-kinesis-video-streams-parser-library#43]
Hello;

So far I have been able to save video from the provided `KinesisVideoExample` which stores the current feed from the stream into a mkv file.  My object now is to store the fragments from an archived media using the `getMediaForFragmentList()` API.  My modification to the KinesisVideoExample gives me a video but the length of the video is not proper.  Let me elaborate.

I am getting the list of fragments first within a time range, which works fine, I can list the fragment numbers, their duration adds up fine (using `getFragmentLengthInMilliseconds()`) to what I requested.  Their size (using `getFragmentSizeInBytes()`) adds up to 7MB.  

Now when I create the video from the stream using this fragment list (using the same way `KinesisVideoExample` creates), the resultant video size is the same as the size of the fragments (which is fine), BUT the video only plays for 1.5 sec and it stops in any media player!  Which gives me the guess that the video might be broken.  I tried other strategies from the `InputStream` for creating the video e.g.

``` java
//Method 1
FileOutputStream out = new FileOutputStream(new File("output.webm"));
IOUtils.copy(in, out);
```

``` java
//Method 2
    byte[] buffer = new byte[8 * 1024];
    int bytesRead;
    while ((bytesRead = in.read(buffer)) != -1) {
        out.write(buffer, 0, bytesRead);
    }
    IOUtils.closeQuietly(in);
    IOUtils.closeQuietly(out);
```
But all of them result in the same broken video file.  What I might be doing wrong here?  Is there something wrong with the `InputStream` that is generated from `getMediaForFragmentList`?  But in that case how come the file size is fine in terms of the size of all the fragments together?

Any pointer will be appreciated.

**Comment by zhiyua-git** [comment]
Hi,

Can you change the java sdk dependency version like below to 1.11.483, then re-import maven dependencies and rerun your app?
 
diff --git a/pom.xml b/pom.xml
index 7cbfecb..dcf56f4 100644
--- a/pom.xml
+++ b/pom.xml
@@ -56,12 +56,12 @@
         <dependency>
             <groupId>com.amazonaws</groupId>
             <artifactId>aws-java-sdk-core</artifactId>
-            <version>1.11.289</version>
+            <version>1.11.483</version>
         </dependency>
         <dependency>
             <groupId>com.amazonaws</groupId>
             <artifactId>aws-java-sdk-kinesisvideo</artifactId>
-            <version>1.11.247</version>
+            <version>1.11.483</version>
         </dependency>
         <dependency>
             <groupId>com.amazonaws</groupId>

Thanks,
-ZH

**Comment by arnamoy10** [comment]
Hi, I just did, but the problem is still there.

My guess is because when I pass the list of fragments to be fetched by `getMediaForFragmentList()`, I do not pass them in sorted order, because I form the list of fragments as follows:

```java
ListFragmentsResult result_fragments = videoMedia.listFragments(request);

//extract the fragment numbers in a list
List<Fragment> fragments = result_fragments.getFragments();
List<String> fragment_numbers = new ArrayList<String>();

for (i = 0; i < fragments.size(); i++) 
    fragment_numbers.add(fragments.get(i).getFragmentNumber()); 
```
Which produces a different order of fragments for `fragment_numbers` every time I run the app.  Do you think if I sort the fragment list according to server timestamp and then pass to `getMediaForFragmentList()`, it will produce the right video?  I will try it now and let you know

**Comment by arnamoy10** [comment]
That was the issue, sorting the fragment list works.  Thanks a lot for your help on this!
