### ISSUE TITLE
Do we have something similar but for NodeJS?

### ISSUE THREAD

**Issue by brahama** [aws/amazon-kinesis-video-streams-parser-library#47]
Just wondering that. Is there perhaps another repo or plans for it?

Thanks guys!

**Comment by gilgameshskytrooper** [comment]
Also wondering if there is a Go implementation for this.

**Comment by MushMal** [comment]
Thanks for the feedback. We are working on collecting data and will take this info account. Currently, only Java parser library is supported. However, the underlying media is in standard MKV format so one could use any other 3rd party parser to get to the bits.

**Comment by gilgameshskytrooper** [comment]
@MushMal I am relatively new to video streaming. Could you please suggest a few 3rd party parsers?

**Comment by MushMal** [comment]
Resolving as stale.

**Comment by piercus** [comment]
@brahama @MushMal @gilgameshskytrooper I have published https://www.npmjs.com/package/kvs-parser today.

Any feedback on this would be appreciated ! :smiley:

**Comment by MushMal** [comment]
I really like the idea of the library. I would imagine AWS folks would be very interested in it. @disa6302, any idea who can help with reviewing this?
