### ISSUE TITLE
Do you have pre-package Lambda Function for Amazon Connect Live Media Streaming?

### ISSUE THREAD

**Issue by casperber07** [aws/amazon-kinesis-video-streams-parser-library#59]
Do you have pre-package Lambda Function for Amazon Connect Live Media Streaming?

**Comment by ranman** [comment]
Hi @casperber07 not at the moment but we will be releasing a project later this year here: https://github.com/amazon-connect/

Feel free to contact me randhunt@amazon.com if you would like more info.

**Comment by MushMal** [comment]
Resolving as stale
