### ISSUE TITLE
Unable to build with mvn or use in Eclipse

### ISSUE THREAD

**Issue by KathyFeiyang** [aws/amazon-kinesis-video-streams-parser-library#60]
Hi, any insights into these problems would be greatly appreciated.

1. After using git clone to get the repository, I can't successfully build with mvn. The error messages I get are the following:

`WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Scanning for projects...
[INFO] 
[INFO] -----< com.amazonaws:amazon-kinesis-video-streams-parser-library >------
[INFO] Building Amazon Kinesis Video Streams Parser Library 1.0.13
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ amazon-kinesis-video-streams-parser-library ---
[INFO] 
[INFO] --- lombok-maven-plugin:1.16.18.1:delombok (delombok) @ amazon-kinesis-video-streams-parser-library ---
[WARNING] Unable to detect tools.jar; java.home is /usr/lib/jvm/java-11-openjdk-amd64
Copying resource file: com/amazonaws/kinesisvideo/parser/examples/.DS_Store
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.597 s
[INFO] Finished at: 2019-06-11T15:20:12-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.projectlombok:lombok-maven-plugin:1.16.18.1:delombok (delombok) on project amazon-kinesis-video-streams-parser-library: Unable to delombok: InvocationTargetException: ExceptionInInitializerError: com.sun.tools.javac.code.TypeTags -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
`

2. I tried importing the maven project using Eclipse as well, but there would be an "Unable to delombok" error in the pom.xml file. 
I also tried to run KinesisVideoExampleTest, in src/test/java. Initially it cannot find KinesisVideo Example in src/main/java. This seems fixed after setting src/main/java to be source folder. However, doing so creates a lot of additional problems with build paths.

I'm currently using:
- Eclipse IDE for Java Developers, Version 4.11.0
- Ubuntu 18.04
- Apache Maven 3.6.0
- Java 11.0.3

Does anyone know how to solve the above problems?

Thank you in advance.

**Comment by mapavia** [comment]
I don't know about 1, but with 2, I think I fixed the "Unable to delombok" by changing the version just before the delombok line in `<artifactId>lombok-maven-plugin</artifactId>
                <version>1.18.8</version>`

I'm quiet new with Java and Eclipse, so I was wondering how did you run KinesisVideoExampleTest? Did you run it in Eclipse by right click > Run As > JUnit Test? Nothing happens on mine, just says "Finished after 0.0XX seconds. Runs: 2/2 (2 skipped)". :(

**Comment by zhiyua-git** [comment]
Hi @mapavia , as the tests are ignored by default, you will need to remove the @Ignore on the test to run it.

**Comment by mapavia** [comment]
OMG. How did I not know about this (definitely a Java Noob). Been bugging me for hours. Anyway, thanks! I hope this gets me somewhere. I guess to more errors.
