### ISSUE TITLE
error while running rtsp stream

### ISSUE THREAD

**Issue by dhrumil-softvan** [aws/amazon-kinesis-video-streams-parser-library#65]
when I run the video file this code gives correct output by recognizing the face and shows output on another kinesis video stream but when I run rtsp video stream, the rekognized video stream shows a blank screen. In cloud watch the error is java.lang.RuntimeException: long term. Here is a full stack trace

java.lang.RuntimeException: long term at org.jcodec.codecs.h264.decode.RefListManager.reorder(RefListManager.java:156) at org.jcodec.codecs.h264.decode.RefListManager.buildRefListP(RefListManager.java:79) at org.jcodec.codecs.h264.decode.RefListManager.getRefList(RefListManager.java:42) at org.jcodec.codecs.h264.decode.SliceDecoder.decodeFromReader(SliceDecoder.java:71) at org.jcodec.codecs.h264.H264Decoder$FrameDecoder.decodeFrame(H264Decoder.java:152) at org.jcodec.codecs.h264.H264Decoder.decodeFrameFromNals(H264Decoder.java:103) at com.amazonaws.kinesisvideo.parser.utilities.H264FrameDecoder.decodeH264Frame(H264FrameDecoder.java:64) at com.amazonaws.kinesisvideo.parser.examples.lambda.H264FrameProcessor.process(H264FrameProcessor.java:104) at com.amazonaws.kinesisvideo.parser.utilities.FrameVisitor$FrameProcessor.process(FrameVisitor.java:73) at com.amazonaws.kinesisvideo.parser.utilities.FrameVisitor$FrameVisitorInternal.visit(FrameVisitor.java:105) at com.amazonaws.kinesisvideo.parser.mkv.MkvDataElement.accept(MkvDataElement.java:128) at com.amazonaws.kinesisvideo.parser.mkv.visitors.CompositeMkvElementVisitor.visitAll(CompositeMkvElementVisitor.java:67) at com.amazonaws.kinesisvideo.parser.mkv.visitors.CompositeMkvElementVisitor.visit(CompositeMkvElementVisitor.java:54) at com.amazonaws.kinesisvideo.parser.mkv.MkvDataElement.accept(MkvDataElement.java:128) at com.amazonaws.kinesisvideo.parser.mkv.StreamingMkvReader.apply(StreamingMkvReader.java:132) at com.amazonaws.kinesisvideo.parser.examples.GetMediaForFragmentListWorker.run(GetMediaForFragmentListWorker.java:64) at com.amazonaws.kinesisvideo.parser.examples.lambda.KinesisVideoRekognitionLambdaExample.processRekognizedOutputs(KinesisVideoRekognitionLambdaExample.java:124) at com.amazonaws.kinesisvideo.parser.examples.lambda.KinesisVideoRekognitionLambdaExample.handleRequest(KinesisVideoRekognitionLambdaExample.java:164) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at lambdainternal.EventHandlerLoader$PojoMethodRequestHandler.handleRequest(EventHandlerLoader.java:259) at lambdainternal.EventHandlerLoader$PojoHandlerAsStreamHandler.handleRequest(EventHandlerLoader.java:178) at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:888) at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:293) at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:64) at java.lang.Class.forName0(Native Method) at java.lang.Class.forName(Class.java:348) at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:114) 

And also I did not understand detectedTime in code. I tried to print serverTimeStamp, producerTimeStamp as well as detectedTime. What I find is serverTimeStamp is always correct. But detectedTime is not always correct it provides a very wrong timestamp.

For examples:
This is serverTimeStamp 1.561984271535E9 which is correct.
And here is detected time 1.5619854765320477E9. Look at the time stamp it is not a valid timestamp.
So, what is the purpose of detectedTime when we have serverTimeStamp? and why detectedTime sometimes provide correct time and sometimes incorrect time?
Also as I attached full stack trace above what does this error mean what I am doing wrong?

**Comment by unicornss** [comment]
> when I run the video file this code gives correct output by recognizing the face and shows output on another kinesis video stream but when I run rtsp video stream, the rekognized video stream shows a blank screen

Could you please confirm if you are able to view the live video stream in the KVS console 
(or HLS player) while streaming from the RTSP camera?

**Comment by dhrumilsheth9** [comment]
Hey, @unicornss thank you for replying. Yes, I was able to view live streaming video. However, I was not able to see the recognized video.

**Comment by MushMal** [comment]
Resolving as stale. Rekognition issue?
