### ISSUE TITLE
Using KinesisVideoRekognitionLambdaExample to put bounding boxes on all objects detected (not just face)

### ISSUE THREAD

**Issue by mapavia** [aws/amazon-kinesis-video-streams-parser-library#66]
Hi, I am now playing with the KinesisVideoRekognitionLambdaExample. It's able to create bounding boxes to faces (with "No prefix" label). I was wondering how I could edit the code to show bounding boxes to all types of objects like bus and cars. Thanks.

**Comment by MushMal** [comment]
You might want to explore the Rekognition forums to get more information.
