### ISSUE TITLE
Builds Failing windows and intellj

### ISSUE THREAD

**Issue by AG-Labs** [aws/amazon-kinesis-video-streams-parser-library#67]
I am following this tutorial which links here.
https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/examples-renderer.html

However the project fails to build. Multiple errors (100) state that they "cannot resolve symbol <x>" KinesisVideoRendererExmple being the first instance of this error.

Further more Lombok could not be initialised.

**Comment by AG-Labs** [comment]
I made numerous changes to the code to get it to work. Should these be updated in the actual repo?

https://github.com/AG-Labs/kinesisStreamer

**Comment by MushMal** [comment]
Resolving as stale. Please try the latest
