### ISSUE TITLE
Running KinesisVideoRekognitionIntegrationExampleTest Error

### ISSUE THREAD

**Issue by Alex-fanfanfan** [aws/amazon-kinesis-video-streams-parser-library#68]
I can only got one picture from this test instead of a video and this is the error message.
It seems there is only one thread worked. Anyone met the same issue?

> ERROR com.amazonaws.kinesisvideo.parser.examples.GetMediaWorker - Failure in GetMediaWorker for streamName <stream_name> java.util.NoSuchElementException: No value present

**Comment by MushMal** [comment]
Could you retry the latest please?
