### ISSUE TITLE
Extract specific frame from the fragment

### ISSUE THREAD

**Issue by JieHuo427** [aws/amazon-kinesis-video-streams-parser-library#69]
I am using kinesis-video-streams-parser-library to extract particular frame from a fragment.
I have the json input
"frameMetaData":  
Frame(trackNumber=1, timeCode=0, keyFrame=true, invisible=false, discardable=false, lacing=NO)",
"fragmentMetaData": "FragmentMetadata(fragmentNumberString=91343852333181492645699654719911616955122530663, serverSideTimestampMillis=1564523828166, producerSideTimestampMillis=722643, fragmentNumber=91343852333181492645699654719911616955122530663, success=true, errorId=0, errorCode=null, millisBehindNow=OptionalLong.empty, continuationToken=Optional.empty)

Does anybody know how I can locate the frame specified by the timeCode and extract the frame?

Thanks!

**Comment by MushMal** [comment]
Resolving due to staleness. Generally, the parser library makes the calls and it's up to your code to handle the frame bits. You could check the timecode that you are looking for and consume the frame bits
