### ISSUE TITLE
KinesisVideoRendererExampleTest rendering video very fast

### ISSUE THREAD

**Issue by flappy007** [aws/amazon-kinesis-video-streams-parser-library#73]
Hi,
I am running the KinesisVideoRendererExampleTest to render the example video vogels_480.mkv and vogels_330.mkv using Jframe but the video renders very fast that is the 30 secs video is rendered in 10 secs. Is there anything that i need to change from my end to get the video rendered as the source.

**Comment by MushMal** [comment]
These are tests which don't have av/sync
