### ISSUE TITLE
Store Kinesis video stream to S3

### ISSUE THREAD

**Issue by ahmedha** [aws/amazon-kinesis-video-streams-parser-library#76]
Hello,

I am able to produce to AWS Kinesis stream, and able to view the media using "Media Preview".   I would like to persist the video for longer term retention (around 30 days), and I am looking into persisting the video stream to S3.  Is there a library or sample/reference code I can use to get started on the project.

Thank you,
Ahmed.

**Comment by MushMal** [comment]
@ahmedha KVS itself can durably persist the stream for any duration (up-to 10 years). You need to set the retention period of the stream either when creating it or you can update it. You can also simply go to AWS KVS console and set the duration.

Check out the following Issue for more info on how to get the MKV fragments which if you choose you can then persist in S3 yourself

https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-java/issues/47#issuecomment-565075601


Marking as resolved. Please open a separate issue for any specifics.

**Comment by ahmedha** [comment]
I am confused, based on docs, the max retention period of videos is 168 hours ( 7 days ).   Can you please point me to docs that I can go longer?

**Comment by MushMal** [comment]
Hmm. https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/API_UpdateDataRetention.html#KinesisVideo-UpdateDataRetention-request-DataRetentionChangeInHours

You can use the max when creating/updating a stream via AWS CLI or directly in the console

**Comment by hameedriswan7** [comment]
@ahmedha  did you stored Kinesis Video Stream in S3? i am also facing same issue.

**Comment by garishsood** [comment]
@ahmedha the 7 day retention is specific to "Kinesis Data Streams" service and not for "Kinesis VIdeo Streams". These two are different and you can store video in a Kinesis VIdeo stream for up to 10 years.

**Comment by hameedriswan7** [comment]
is any possible way to store kinesis video stream in s3 like 30 days partition of video?

**Comment by Sandip123697** [comment]
I want to store a kinesis video stream into S3 bucket. Is there any documentation through which I can perform this task?
