### ISSUE TITLE
Need Feature to get Kinesis Video Stream for Rekognition for Age,Gender and Emotions

### ISSUE THREAD

**Issue by hameedriswan7** [aws/amazon-kinesis-video-streams-parser-library#77]
Hi all,

Currently i can Stream the RTSP camera using PutMedia.
Then we create Data Stream for that KVS to start Stream Processor for getting  Rekognition of that stream.
 But for Live Stream AWS provide FaceMatching API only.So we cannot get  Age,Gender and Emotions. 

if any feature available for above scenario please provide links or Docs.?

For Uploading video to Rekognition . AWS provide API getting  Age,Gender and Emotions.
So that process we implement Getmedia for getting Live stream as Uploading Video for Rekognition.

i can get live stream in local storage of system. using {StreamingMkvReader} and {FragmentMetadataVisitor} ana {OutputSegmentMerger}

Reference Link provide by @zhiyua-git  :
https://github.com/aws/amazon-kinesis-video-streams-parser-library/blob/master/src/main/java/com/amazonaws/kinesisvideo/parser/examples/KinesisVideoExample.java#L199

By using OutputSegmentMerger it make live stream as single video.But i need 30min once partition of video for uploading to S3 for start Rekognition. 

is any feature available for get Kinesis Video Stream for Rekognition for Age,Gender and Emotions?

**Comment by MushMal** [comment]
Resolving this issue as it's very generic. Please cut issues which are more targeted.
