### ISSUE TITLE
Consumer hanging - Detected time code going back from Optional[2283360] to 0

### ISSUE THREAD

**Issue by lukasz-gawron** [aws/amazon-kinesis-video-streams-parser-library#79]
Hi,
We want to use AWS Kinesis Video Streams for our video pipeline working in realtime.
For test purposes we are using kvssink as producer to push mp4 file with 4k video.

**Our setup**
**Producer**
Built from two Gstreamer pipelines.

`filesrc location=/root/bin/producer/video/movie.mp4 ! qtdemux  ! video/x-h264,format=avc,alignment=au ! h264parse ! video/x-h264,stream-format=avc,alignment=au ! appsink name=H264_SINK caps=video/x-h264,stream-format=avc,alignment=au `

and

`appsrc name=video_src caps=video/x-h264,stream-format=avc,alignment=au ! queue  ! video/x-h264,stream-format=avc,alignment=au !  kvssink  stream-name="StreamName" credential-path=\"/root/.aws/kinesis_credentials\"  aws-region=\"eu-west-1\" streaming-type=offline`

Video frames are slightly modified in appsink callback, and pushed to appsrc which is than pushed to Kinesis through kvssink.

**Kinesis stream**
Stream have retention period set to 1h.

**Consumer is based on example:**
https://github.com/aws/amazon-kinesis-video-streams-parser-library/blob/master/src/main/java/com/amazonaws/kinesisvideo/parser/examples/KinesisVideoGStreamerPiperExample.java

But we've done few modifications, most outstanding are:
https://github.com/aws/amazon-kinesis-video-streams-parser-library/blob/2e93ba3ec843677c3128a6b4355e67f340ef0859/src/main/java/com/amazonaws/kinesisvideo/parser/examples/KinesisVideoGStreamerPiperExample.java#L125

changed to 100000 seconds.

And SelectorType changed from EARLIEST to NOW.
https://github.com/aws/amazon-kinesis-video-streams-parser-library/blob/2e93ba3ec843677c3128a6b4355e67f340ef0859/src/main/java/com/amazonaws/kinesisvideo/parser/examples/KinesisVideoGStreamerPiperExample.java#L105

**Problem**
We spot that after ~38 mins, consumer hangs with following log printed:
**`2020-02-11 10:52:40 INFO  OutputSegmentMerger:Detected time code going back from Optional[2283360] to 0, state from BUFFERING_CLUSTER_START to DONE`**

**Reason**
We’ve narrowed reason of this to be producer resetting FragmentTimeCode to 0, occuring after  refreshing StreamingToken. Below are logs from this process.

```
INFO - writeHeaderCallback(): RequestId: 81c1be81-8acf-46ef-a844-bc43a7bcba7e
2020-02-11 10:52:38 [140096828532480] DEBUG - getStreamingEndpointCurlHandler(): GetStreamingEndpoint API response: {"DataEndpoint":"https://s-5ac677c0.kinesisvideo.eu-west-1.amazonaws.com"}
2020-02-11 10:52:38 [140096828532480] INFO - getStreamingEndpointResultEvent(): Get streaming endpoint result event.
2020-02-11 10:52:38 [140096828532480] DEBUG - stepStateMachine(): State Machine - Current state: 0x0000000000000020, Next state: 0x0000000000000010
2020-02-11 10:52:38 [140096828532480] INFO - getStreamingTokenResultEvent(): Get streaming token result event
```

**FragmentTimeCode before refresh was 2283360**

`2020-02-11 10:52:37 [140096836925184] DEBUG - postWriteCallback(): Curl post body write function for stream with handle: LatencyTestStream and upload handle: 0 returned: {"EventType":"BUFFERING","FragmentTimecode":2283360,"FragmentNumber":"91343852333181857040777858611842905773666046157"}`

**Next Fragment time code  after refresh is 0.**

`DEBUG - postWriteCallback(): Curl post body write function for stream with handle: LatencyTestStream and upload handle: 1 returned: {"EventType":"BUFFERING","FragmentTimecode":0,"FragmentNumber":"91343852333181858244055576797232533531246195260"}`

**Consumer is hanging in that scenario for around 8 mins and than consume again**
```
2020-02-11 11:00:10 INFO  ContinuousGetMediaWorker:Start processing GetMedia called for stream LatencyTestStream response 200 requestId e9a97d96-70af-24f7-bf15-f6ec18693abc
s2020-02-11 11:00:10 INFO  ContinuousGetMediaWorker:Start processing GetMedia called for stream LatencyTestStream response 200 requestId e9a97d96-70af-24f7-bf15-f6ec18693abc
2020-02-11 11:00:10 INFO  MkvChildElementCollector:MkvChildElementCollector for element EBMLTypeInfo(id=374648427, name=Tracks, level=1, type=MASTER, isRecursive=false)
s2020-02-11 11:00:10 INFO  MkvChildElementCollector:MkvChildElementCollector for element EBMLTypeInfo(id=374648427, name=Tracks, level=1, type=MASTER, isRecursive=false)
2020-02-11 11:00:10 INFO  MkvChildElementCollector:MkvChildElementCollector for element EBMLTypeInfo(id=440786851, name=EBML, level=0, type=MASTER, isRecursive=false)
s2020-02-11 11:00:10 INFO  MkvChildElementCollector:MkvChildElementCollector for element EBMLTypeInfo(id=440786851, name=EBML, level=0, type=MASTER, isRecursive=false)
```
I assume all of that is related to an example was not prepared for long consumption, and some cases are not handled.

**Any help in:**
* suggesting what changes we would have to do on example consumer  to handle such situation. 
Current idea would be to apply suggestion from this issue https://github.com/aws/amazon-kinesis-video-streams-parser-library/issues/16 and retry GetMedia call.

* suggesting what to set on producer side to prevent FragmentTimeCode being reset or extend this period when it should be reset to be more than 38 mins.
* any other feedback about our configuration, which may help improved  our code is welcome.

Best regards,
Lukasz

**Comment by chehefen** [comment]
Hi, we are aware of this issue and we are trying to come up with a proper fix. Before that, you can avoid the parser timecode going back to zero issue by using absolute frame timestamp and configure the producer to be in absolute timestamp mode. You can achieve that by adding file-start-time param to the kvssink plugin and set it to the epoch time when the clip was captured  in seconds. By setting file-start-time, plugin will set producer to absolute timestamp mode, and add file-start-time to each frame.

**Comment by lukasz-gawron** [comment]
Thank you for your advice. It helped.

Lukasz
