### ISSUE TITLE
save streams into as png format local disk

### ISSUE THREAD

**Issue by varun-tangoit** [aws/amazon-kinesis-video-streams-parser-library#80]
Hi,

I try to save each frame into image png format, while i can able get live kinesis video viewer, but i don't know how to save images locally. I did piece code in FrameRendererVisitor module, but frames not save locally. Please help me out from this issue.
After that
AWTUtil.toBufferedImage(rgb, renderImage);
try {
System.out.println("writing into local disk");
ImageIO.write(renderImage, "png", new File(String.format("frame-capture-%s.png", UUID.randomUUID())));
} catch (IOException e) {
log.warn("Couldn't convert to a PNG", e);
}

**Comment by AakashBasu** [comment]
Hey Varun,

We're trying to arrive where you've already reached.

What I could achieve: Using GStreamer to push data from webcam to Kinesis Video Stream using the Producer SDK.

What is left: Struggling to prepare the Parser Library and consume the video as frames. Can you give me a link as in which steps did you follow for the downstream part?

Great to see that you asked this question, mine is exactly the same use case of saving frames as images.

**Comment by MushMal** [comment]
Sorry this issue went stale. In general, saving PNG will depend on what your original stream is. If it's an H264 encoded video for example, then you will need to decode the frames and then store the bitmaps. Resolving as stale - please cut new issues related to the parser library and we will try to help
