### ISSUE TITLE
Pipe audio bytes to media player

### ISSUE THREAD

**Issue by faizaanshah** [aws/amazon-kinesis-video-streams-parser-library#89]
I parsed amazon connect call (live) via this library in a lambda function, and now I need those bytes to be playable in my application in JS. 
I dont know if its right to open an issue for this or not, but I need guidance.
Here are the cloudwatch logs:
![cloudwatch1](https://user-images.githubusercontent.com/22859078/80055122-5f330d00-853a-11ea-8030-41ef4b5cf855.PNG)
![cloudwatch2](https://user-images.githubusercontent.com/22859078/80055126-60643a00-853a-11ea-8092-25527e0cb98a.PNG)
PS: I didnt bother printing this bytearray.

**Comment by MushMal** [comment]
Assuming you are streaming h264 content you will need to find a way to decode those and rasterize. You will need to write an MSE application for the browser. We don't haver a ready player for the raw elementary streams

**Comment by MushMal** [comment]
Resolving as stale
