### ISSUE TITLE
How to extract simpleblock timecode value

### ISSUE THREAD

**Issue by varun-tangoit** [aws/amazon-kinesis-video-streams-parser-library#95]
We want to extract each simpleblock timecode value into local textfile. Im currently using kinesisVideoExample module using write mkv file locally at the same i want those timecode values also. Could you please help me out, is there any reservered keyword using can we able to get value?

```
> <Cluster>
>   <Timecode>1589878994265</Timecode>
>   <SimpleBlock>
>     <track>1</track>
>     **<timecode>1589878994.265</timecode>**
>     <keyframe/>
> -------
> ------
> ---

```

**Comment by MushMal** [comment]
There are some samples in the parser. Recommend looking through the samples to get more info.

Here is an example on hot to get the frame bits :https://github.com/aws/amazon-kinesis-video-streams-parser-library/blob/e35344fd9f22ac128b55604c400764f3a80e71fe/src/main/java/com/amazonaws/kinesisvideo/parser/utilities/FrameVisitor.java#L119


Here is the declaration of the timecode: https://github.com/aws/amazon-kinesis-video-streams-parser-library/blob/b72c4d82a1856ad66cb74430f82dcdbfce5dabe2/src/main/java/com/amazonaws/kinesisvideo/parser/mkv/Frame.java#L39


Please resolve if your question is answered.

**Comment by MushMal** [comment]
Resolving
